version: "3.8"
services:
  medusa-admin:
    user: "${UID}:${GID}"
    env_file:
      - .env
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    image: admin-panel:starter
    container_name: medusa-admin
    depends_on:
      - medusa-api
    ports:
      - "7000:7000"
    volumes:
      - ./admin-panel:/app/

  medusa-api:
    user: "${UID}:${GID}"
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: Dockerfile
    image: backend:starter
    container_name: medusa-api
    depends_on:
      - medusa-postgres
      - medusa-redis
    environment:
      DATABASE_URL: postgresql://${MEDUSA_POSTGRES_USER}:${MEDUSA_POSTGRES_PASSWORD}@medusa-postgres/${MEDUSA_POSTGRES_DB}
      REDIS_URL: redis://medusa-redis
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - ./api:/app/medusa

  medusa-postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - ./.medusa_pgsql_storage:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${MEDUSA_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MEDUSA_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MEDUSA_POSTGRES_DB}

  medusa-minio:
    image: minio/minio
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - ./.medusa_minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data

  medusa-redis:
    image: redis
    expose:
      - 6379
