version: "3.8"
services:
  admin-panel:
    user: "${UID}:${GID}"
    env_file:
      - .env
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    image: admin-panel:starter
    container_name: medusa-admin
    ports:
      - "7000:7000"
    volumes:
      - ./admin-panel:/app/

  api:
    user: "${UID}:${GID}"
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: Dockerfile
    image: backend:starter
    container_name: medusa-api
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://redis
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - ./api:/app/medusa

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  minio:
    image: minio/minio
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data

  redis:
    image: redis
    expose:
      - 6379

volumes:
  minio_storage: {}
